module Solargraph
  module Dragonruby
    VERSION: String

    class Convention < Solargraph::Convention::Base
      STUBS_DIR: String

      def self.pins: () -> Array[Solargraph::Pin::Base]

      def global: (untyped _object) -> Solargraph::Environ
    end

    class MacroNode < Solargraph::Parser::NodeProcessor::Base
      MACROS: Hash[Symbol, String]

      def process: () -> bool
    end
  end
end
